[tool.poetry]
name = "examon"
version = "0.4.0"
description = ""
authors = ["Jarrod Folino <jdfolino@icloud.com>"]
packages = [{include = "examon"}]

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"
pygments = "^2.13.0"
inquirer = "^3.1.1"
simple-term-menu = "^1.6.1"
examon-core = "0.5.6"

[tool.poetry.dev-dependencies]
pytest = "7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
